-- Read-only verification for Armando's provisional fries/nachos/quesadillas/sides batch 3.
begin;
set transaction read only;
do $$
declare
  tenant uuid;
  menu uuid;
  removals uuid;
  extras uuid;
  rolled_choice uuid;
  target_count integer;
  with_removals integer;
  with_extras integer;
  base_only integer;
begin
  select id into strict tenant from public.restaurants where slug='armandos' and is_active;
  if tenant <> '3d87585a-ff4b-4ae1-bef6-4e1e559cb04f'::uuid then raise exception 'Wrong Armando staging tenant'; end if;
  select id into strict menu from public.menus where restaurant_id=tenant and name='Main Menu' and is_published;
  select id into strict removals from public.modifier_groups where restaurant_id=tenant and source_system='menu-man-demo' and source_group_id='remove-ingredients' and is_active;
  select id into strict extras from public.modifier_groups where restaurant_id=tenant and name='Add extras' and is_active;
  select id into strict rolled_choice from public.modifier_groups where restaurant_id=tenant and source_system='menu-man-demo' and source_group_id='rolled-taco-chicken-or-beef' and is_active;

  create temporary table expected_batch3(source_item_id text primary key,item_name text not null,price_cents integer not null) on commit drop;
  insert into expected_batch3 values
    ('421785797','Adobada Chips',1699),('10770317768','Adobada Fries with Sour Cream',1699),('198880554','Adobada Quesadilla',1325),
    ('10608873268','Birria Fries',1465),('10609047987','Birria Nachos',1475),('9813230337','Cabeza Quesadilla',1399),
    ('198880523','Carne Asada Chips',1899),('198880524','Carne Asada Fries',1899),('8570438359','Carne Asada Fries with Beans',1676),
    ('8286200667','Carne Asada Fries with Beans and Sour Cream – No Guacamole',1899),('10891185528','Carne Asada Fries with Picó de Gallo',1899),
    ('759912715','Carne Asada Fries with Sour Cream',1999),('8286730317','Carne Asada Fries with Sour Cream – No Guacamole',1878),
    ('8287922962','Carne Asada Fries with Sour Cream, Rice, and Beans',1845),('5995006478','Carne Asada Nachos with Beans, Onion, and Cilantro',1624),
    ('1169941272','Carne Asada Nachos with Sour Cream',1799),('198880556','Carne Asada Quesadilla',1399),('5336575300','Carnitas Quesadilla',1399),
    ('198880551','Cheese Quesadilla',625),('198880553','Chicken Quesadilla',1399),('6917687049','Chile Verde Nachos',1399),
    ('198880559','Chips and Guacamole',799),('32960992457','Chips and Guacamole No Cheese',699),('198880561','Chips and Salsa',499),('198880557','French Fries',325),
    ('198880562','Half-Order Carne Asada Chips',1699),('198880563','Half-Order Carne Asada Fries',1699),('759912532','Half-Order Carne Asada Fries with Sour Cream',1799),
    ('2222103720','Large Chicken Nachos',1689),('5347103892','Large Ground Beef Fries with Rice, Cheese, and Sour Cream',1525),('27634029237','Large Veggie Fries',1199),
    ('5613241909','Quesabirria',1499),('44177153501','Shredded Beef Nachos Bell Peppers Onion',1599),('198880552','Shrimp Quesadilla',1378),
    ('358347767','Small Surf and Turf Fries',1699),('27631629582','Small Veggie Fries',999),('759911924','Super Nachos',1999),
    ('5337571594','Super Rolled Tacos',1399),('358347340','Surf and Turf Fries',1899),('3871320158','Surf and Turf Quesadilla',1499),
    ('4921379008','Trio Fries with Shrimp, Chicken, and Carne Asada',1999),('9830707325','Two Chiles Rellenos A la Carte',999);
  if (select count(*) from expected_batch3)<>42 then raise exception 'Contract manifest is not 42 items'; end if;
  if exists(select 1 from expected_batch3 expected left join public.menu_items item on item.restaurant_id=tenant and item.source_system='doordash' and item.source_item_id=expected.source_item_id left join public.menu_section_items placement on placement.item_id=item.id left join public.menu_sections section on section.id=placement.section_id and section.menu_id=menu where item.id is null or item.name<>expected.item_name or item.price_cents<>expected.price_cents or item.is_orderable is distinct from true or section.name is distinct from 'Carne Asada Fries, Nachos, Quesadillas & Sides' group by expected.source_item_id having count(item.id)<>1 or count(section.id)<>1) then raise exception 'Source identity, uniqueness, item name, price, section, or orderability mismatch'; end if;
  select count(*) into target_count from public.menu_items item join public.menu_section_items placement on placement.item_id=item.id join public.menu_sections section on section.id=placement.section_id where item.restaurant_id=tenant and item.source_system='doordash' and section.menu_id=menu and section.name='Carne Asada Fries, Nachos, Quesadillas & Sides';
  if target_count<>42 then raise exception 'Target section placement count is %',target_count; end if;
  select count(*) filter(where exists(select 1 from public.menu_item_modifier_groups a where a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id=removals and a.is_active)), count(*) filter(where exists(select 1 from public.menu_item_modifier_groups a where a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id=extras and a.is_active)), count(*) filter(where not exists(select 1 from public.menu_item_modifier_groups a where a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id in(removals,extras) and a.is_active)) into with_removals,with_extras,base_only from public.menu_items item join expected_batch3 e on e.source_item_id=item.source_item_id where item.restaurant_id=tenant and item.source_system='doordash';
  if (with_removals,with_extras,base_only) is distinct from (37,14,5) then raise exception 'Customization counts differ: removals %, extras %, base-only %',with_removals,with_extras,base_only; end if;
  if (select count(*) from public.modifier_groups where restaurant_id=tenant and name='Add extras' and is_active)<>1 then raise exception 'Expected exactly one tenant-owned Add extras group'; end if;
  if (select count(*) from public.modifier_options where restaurant_id=tenant and modifier_group_id=extras and is_active)<>3
     or not exists(select 1 from public.modifier_options where restaurant_id=tenant and modifier_group_id=extras and name='Guacamole' and is_active and default_price_adjustment_cents=150)
     or not exists(select 1 from public.modifier_options where restaurant_id=tenant and modifier_group_id=extras and name='Sour Cream' and is_active and default_price_adjustment_cents=75)
     or not exists(select 1 from public.modifier_options where restaurant_id=tenant and modifier_group_id=extras and name='Cheese' and is_active and default_price_adjustment_cents=100) then raise exception 'Armando extras prices/options are incorrect'; end if;
  if exists(select 1 from public.modifier_options where restaurant_id=tenant and modifier_group_id=removals and is_active and (default_price_adjustment_cents<>0 or is_default)) then raise exception 'Removal options must be zero-price and non-default'; end if;

  -- Every active removal must name an ingredient in that item's own source copy.
  if exists(select 1 from public.menu_items item join expected_batch3 e on e.source_item_id=item.source_item_id join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id=removals and a.is_active join public.modifier_options o on o.restaurant_id=tenant and o.modifier_group_id=removals and o.is_active left join public.menu_item_modifier_option_overrides x on x.restaurant_id=tenant and x.menu_item_id=item.id and x.modifier_option_id=o.id where item.restaurant_id=tenant and item.source_system='doordash' and coalesce(x.is_active,true) and not ((o.source_option_id='guacamole' and concat_ws(' ',item.name,item.description) ~* 'guacamole|avocado') or (o.source_option_id='pico' and concat_ws(' ',item.name,item.description) ~* 'pico|pic.{0,3}[[:space:]]*de gallo') or (o.source_option_id='cheese' and concat_ws(' ',item.name,item.description) ~* 'cheese') or (o.source_option_id='sour-cream' and concat_ws(' ',item.name,item.description) ~* 'sour[[:space:]]*cream') or (o.source_option_id='beans' and concat_ws(' ',item.name,item.description) ~* 'beans?') or (o.source_option_id='rice' and concat_ws(' ',item.name,item.description) ~* 'rice') or (o.source_option_id='onion' and concat_ws(' ',item.name,item.description) ~* 'onion') or (o.source_option_id='cilantro' and concat_ws(' ',item.name,item.description) ~* 'cilantro') or (o.source_option_id='cabbage' and concat_ws(' ',item.name,item.description) ~* 'cabbage') or (o.source_option_id='lettuce' and concat_ws(' ',item.name,item.description) ~* 'lettuce') or (o.source_option_id='bell-peppers' and concat_ws(' ',item.name,item.description) ~* 'bell peppers?|green peppers?') or (o.source_option_id='fries' and concat_ws(' ',item.name,item.description) ~* 'fries') or (o.source_option_id='potatoes' and concat_ws(' ',item.name,item.description) ~* 'potato') or (o.source_option_id='avocado' and concat_ws(' ',item.name,item.description) ~* 'avocado'))) then raise exception 'Removal option leakage: an ingredient is absent from item copy'; end if;
  if exists(select 1 from public.menu_items item join public.menu_section_items p on p.item_id=item.id join public.menu_sections s on s.id=p.section_id and s.menu_id=menu and s.name='Carne Asada Fries, Nachos, Quesadillas & Sides' join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id=removals and a.is_active join public.modifier_options o on o.restaurant_id=tenant and o.modifier_group_id=removals and o.source_option_id='guacamole' and o.is_active left join public.menu_item_modifier_option_overrides x on x.restaurant_id=tenant and x.menu_item_id=item.id and x.modifier_option_id=o.id where item.restaurant_id=tenant and item.source_system='doordash' and item.name ~* 'no[[:space:]-]*guacamole' and coalesce(x.is_active,true)) then raise exception 'Explicit No Guacamole item exposes Remove Guacamole'; end if;
  if exists(select 1 from public.menu_items item join public.menu_section_items p on p.item_id=item.id join public.menu_sections s on s.id=p.section_id and s.menu_id=menu and s.name='Carne Asada Fries, Nachos, Quesadillas & Sides' join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id=removals and a.is_active join public.modifier_options o on o.restaurant_id=tenant and o.modifier_group_id=removals and o.source_option_id='cheese' and o.is_active left join public.menu_item_modifier_option_overrides x on x.restaurant_id=tenant and x.menu_item_id=item.id and x.modifier_option_id=o.id where item.restaurant_id=tenant and item.source_system='doordash' and item.name ~* 'no[[:space:]-]*cheese' and coalesce(x.is_active,true)) then raise exception 'Explicit No Cheese item exposes Remove Cheese'; end if;
  -- Do not offer a paid ingredient already included in the source item, including any item in this batch.
  if exists(select 1 from public.menu_items item join expected_batch3 e on e.source_item_id=item.source_item_id join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.modifier_group_id=extras and a.is_active join public.modifier_options o on o.restaurant_id=tenant and o.modifier_group_id=extras and o.is_active left join public.menu_item_modifier_option_overrides x on x.restaurant_id=tenant and x.menu_item_id=item.id and x.modifier_option_id=o.id where item.restaurant_id=tenant and item.source_system='doordash' and coalesce(x.is_active,true) and ((o.name='Guacamole' and concat_ws(' ',item.name,item.description) ~* 'guacamole|avocado') or (o.name='Sour Cream' and concat_ws(' ',item.name,item.description) ~* 'sour[[:space:]]*cream') or (o.name='Cheese' and concat_ws(' ',item.name,item.description) ~* 'cheese'))) then raise exception 'Included ingredient is exposed again as a paid extra'; end if;
  if exists(select 1 from public.menu_items item join expected_batch3 e on e.source_item_id=item.source_item_id join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.is_active join public.modifier_groups g on g.restaurant_id=tenant and g.id=a.modifier_group_id where item.restaurant_id=tenant and item.source_system='doordash' and g.name not in('Remove ingredients','Add extras','Choose chicken or beef')) then raise exception 'Unexpected active modifier group leakage'; end if;
  if exists(select 1 from public.menu_items item join expected_batch3 e on e.source_item_id=item.source_item_id join public.menu_item_modifier_groups a on a.menu_item_id=item.id and a.is_active join public.modifier_groups g on g.id=a.modifier_group_id where item.restaurant_id=tenant and (a.restaurant_id is distinct from tenant or g.restaurant_id is distinct from tenant)) then raise exception 'Cross-tenant modifier attachment detected'; end if;
  if exists(select 1 from public.menu_items item join expected_batch3 e on e.source_item_id=item.source_item_id join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.is_active join public.modifier_groups g on g.restaurant_id=tenant and g.id=a.modifier_group_id where item.restaurant_id=tenant and item.source_system='doordash' and g.name='Choose your meat') then raise exception 'Fixed protein item received a meat selector'; end if;
  if exists(select 1 from public.menu_items item join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=item.id and a.is_active join public.modifier_groups g on g.restaurant_id=tenant and g.id=a.modifier_group_id where item.restaurant_id=tenant and g.source_system='menu-man-demo' and g.source_group_id='rolled-taco-chicken-or-beef' and item.source_item_id<>'5337571594') then raise exception 'Chicken/beef rolled-taco choice leaked to another item'; end if;
  if (select count(*) from public.menu_item_modifier_groups where restaurant_id=tenant and menu_item_id=(select id from public.menu_items where restaurant_id=tenant and source_system='doordash' and source_item_id='5337571594') and modifier_group_id=rolled_choice and is_active and min_selections=1 and max_selections=1)<>1 or (select count(*) from public.modifier_options where restaurant_id=tenant and modifier_group_id=rolled_choice and is_active and default_price_adjustment_cents=0)<>2 then raise exception 'Rolled taco required choice has no valid zero-price path'; end if;
  if exists(select 1 from public.menu_items i join public.menu_item_modifier_groups a on a.restaurant_id=tenant and a.menu_item_id=i.id and a.is_active and a.min_selections>0 where i.restaurant_id=tenant and i.is_orderable and not exists(select 1 from public.modifier_options o left join public.menu_item_modifier_option_overrides x on x.restaurant_id=tenant and x.menu_item_id=i.id and x.modifier_option_id=o.id where o.restaurant_id=tenant and o.modifier_group_id=a.modifier_group_id and o.is_active and coalesce(x.is_active,true))) then raise exception 'Required group has no active option path'; end if;
  if (select count(*) from public.menu_items where restaurant_id=tenant and is_orderable)<>307 then raise exception 'Whole menu orderable count is not 307'; end if;
  if (select count(*) from public.menu_items i join public.menu_section_items p on p.item_id=i.id join public.menu_sections s on s.id=p.section_id and s.menu_id=menu and s.name='Street Tacos' where i.restaurant_id=tenant and i.source_system='doordash' and i.source_item_id in('359794279','359796582') and not i.is_orderable)<>2 then raise exception 'Both 20-taco party packs must remain held'; end if;
end $$;
rollback;
